In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [23]:

file_path = "/content/drive/MyDrive/Case_Study_02/elektrik_veri.xlsx"

# Tüm sayfaları tek seferde oku
dfs = pd.read_excel(file_path, sheet_name=None, engine="openpyxl")

print("Sayfa isimleri:", list(dfs.keys()))

df_tahsilat = dfs["Tahsilat"]
df_tahsilat_1 = dfs["Tahsilat 1"]
df_tahakkuk = dfs["Tahakkuk"]
df_tahakkuk_1 = dfs["Tahakkuk 1"]
df_tahakkuk_2 = dfs["Tahakkuk 2"]

print(
    f"Tahsilat: {df_tahsilat.shape} | "
    f"Tahsilat 1: {df_tahsilat_1.shape} | "
    f"Tahakkuk: {df_tahakkuk.shape} | "
    f"Tahakkuk 1: {df_tahakkuk_1.shape} | "
    f"Tahakkuk 2: {df_tahakkuk_2.shape}"
)

Sayfa isimleri: ['Tahsilat', 'Tahsilat 1', 'Tahakkuk', 'Tahakkuk 1', 'Tahakkuk 2']
Tahsilat: (636993, 9) | Tahsilat 1: (917632, 22) | Tahakkuk: (124818, 10) | Tahakkuk 1: (765657, 10) | Tahakkuk 2: (295223, 10)

After running the above cells, you can find the path to your `elektrik_veri.xlsx` file and update the `file_path` variable in the previous code cell.

In [24]:
df_tahsilat.info()
df_tahakkuk.info()

df_tahakkuk.describe()
df_tahakkuk.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636993 entries, 0 to 636992
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Şube                   636993 non-null  object
 1   Kasa                   636993 non-null  object
 2   İlçe                   636993 non-null  object
 3   Söz.hsp.(bağımsız)     636993 non-null  int64
 4   Tahsilat Tarihi        636993 non-null  datetime64[ns]
 5   Nakit Tahsilat         523 non-null     float64
 6   Mahsuben Tahsilat      7542 non-null    float64
 7   Kredi Kartı Tahsilatı  0 non-null       float64
 8   Banka Tahsilatı        628933 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 43.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124818 entries, 0 to 124817
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   il                 124818 non-null  object
 1   ilce               124818 non-null  object
 2   sozlesme_hesap_no  124818 non-null  int64
 3   mali_yil_donem     124818 non-null  object
 4   fatura_tarihi      124818 non-null  object
 5   kayit_tarihi       124818 non-null  object
 6   vade_tarihi        124818 non-null  object
 7   hesap_sinifi       124818 non-null  object
 8   Hesap Sınıfı       124818 non-null  object
 9   kwh                124818 non-null  float64
dtypes: float64(1), int64(1), object(8)
memory usage: 9.5+ MB

,il,ilce,sozlesme_hesap_no,mali_yil_donem,fatura_tarihi,kayit_tarihi,vade_tarihi,hesap_sinifi,Hesap Sınıfı,kwh
0,AMASYA,HAMAMÖZÜ,917576806,2023-01-01,2023-01-12,2023-03-06,2023-01-23,M001,Mesken,1.79
1,AMASYA,HAMAMÖZÜ,917576806,2023-01-01,2023-02-09,2023-05-11,2023-02-20,M001,Mesken,2.60
2,AMASYA,HAMAMÖZÜ,917576806,2023-02-01,2023-02-09,2023-05-11,2023-02-20,M001,Mesken,1.23
3,AMASYA,HAMAMÖZÜ,917576806,2023-02-01,2023-03-10,2023-05-11,2023-03-20,M001,Mesken,2.56
4,AMASYA,HAMAMÖZÜ,917576806,2023-03-01,2023-03-10,2023-05-11,2023-03-20,M001,Mesken,1.35

In [25]:
#Benzersiz Müşteri Sayıları
print("Hamamözü:", df_tahakkuk['sozlesme_hesap_no'].nunique())
print("Gümüşhacıköy:", df_tahakkuk_1['sozlesme_hesap_no'].nunique())
print("Göynücek:", df_tahakkuk_2['sozlesme_hesap_no'].nunique())

Hamamözü: 2981
Gümüşhacıköy: 18190
Göynücek: 7128

In [26]:
#Tahakkuk Verilerini Birleştirme
df_all = pd.concat([df_tahakkuk, df_tahakkuk_1, df_tahakkuk_2])
print("Toplam kayıt:", df_all.shape)

Toplam kayıt: (1185698, 10)

In [27]:
#Veri Kalitesi Kontrolü (eksik veri)
df_all.isna().sum()

il                   0
ilce                 0
sozlesme_hesap_no    0
mali_yil_donem       0
fatura_tarihi        0
kayit_tarihi         0
vade_tarihi          0
hesap_sinifi         0
Hesap Sınıfı         0
kwh                  0
dtype: int64

In [28]:
#Veri Kalitesi Kontrolü (negatif tüketim)
df_all[df_all['kwh'] < 0].head()

,il,ilce,sozlesme_hesap_no,mali_yil_donem,fatura_tarihi,kayit_tarihi,vade_tarihi,hesap_sinifi,Hesap Sınıfı,kwh
23573,AMASYA,HAMAMÖZÜ,7904741733,2025-03-01,2025-04-14,2025-06-10,2025-04-22,M001,Mesken,-1242.99
23576,AMASYA,HAMAMÖZÜ,7904741733,2025-04-01,2025-04-14,2025-06-10,2025-04-22,M001,Mesken,-733.04
28413,AMASYA,HAMAMÖZÜ,469034964,2023-10-01,2023-10-11,2023-11-28,2023-10-23,M001,Mesken,-1.04
70626,AMASYA,HAMAMÖZÜ,7722066065,2023-10-01,2023-10-23,2023-11-28,2023-11-02,M001,Mesken,-1.34
55683,AMASYA,GÜMÜŞHACIKÖY,2945215788,2024-02-01,2024-04-15,2024-06-15,2024-03-25,M001,Mesken,-374.09

In [29]:
#Veri Kalitesi Kontrolü (genel istatistik)
df_all['kwh'].describe()

count    1.185698e+06
mean     9.264207e+01
std      9.504052e+02
min     -2.537064e+04
25%      1.801000e+01
50%      4.662000e+01
75%      8.000000e+01
max      1.535757e+05
Name: kwh, dtype: float64

In [30]:
#Hesap Sınıfına Göre Tablo Oluşturma
hesap_stats = df_all.groupby("Hesap Sınıfı")["kwh"].agg(["mean","median","std","count"])
hesap_stats.sort_values("mean", ascending=False)

,mean,median,std,count
Hesap Sınıfı,,,,
Karayolları Genel Müdürlüğü Aydınlatma,30203.431220,36810.900,16963.572539,41
Aritma Tesisleri,16594.174857,16186.910,11656.705924,35
Lisansız Üreticiler,16155.254444,322.320,35926.424902,180
Sanayi,7293.799626,1531.680,13716.343807,187
İçme-Kullanma Suyu (Belediye),5213.509281,400.020,8948.065839,417
Tarımsal Faaliyetler (Kooperatif),3779.290533,282.720,9426.941321,1632
Lisansız Üreticiler - Resmi Daire,1195.051389,770.625,1229.579483,36
"Resmi SAĞLIK KURULUŞLARI,RESMİ SPOR TES.",1154.739118,239.905,3804.865088,442
"Resmi Üniversite,Yük.Okul,Kurs,Yurt,Okul",883.888739,285.410,1435.311536,476
1 SAYILI CETVELDE YER ALAN KAMU İDARESİ,688.441598,23.860,3911.912974,8500
Köy İçme Suyu Temini ve Dağıtımı Tesisi,676.935305,208.655,1212.334580,2460
Belediye,600.581235,78.270,3350.978976,2097
Resmi Daire,579.850961,150.830,1693.273715,1373
Tarımsal Faaliyetler (Şahıs),541.608449,16.150,3627.959619,17266
Süt Toplama Merkezi,430.637801,187.405,1131.991530,1128
Ölçümsüz Aboneler (Resmi Daire),395.160435,74.400,595.389083,46
İç Tüketim,270.340000,228.680,148.809345,124
İktisadi İşletmeleri Hariç Dernek ve Vkf,183.485878,89.760,205.340833,279
Ticari Faaliyet - Yazıhane,167.827953,41.600,781.762054,91298
Diyanet Kuran Kursu,167.135000,22.115,526.354274,42
Şantiye ve Geçici Aboneler,136.952881,28.420,798.495578,6706
Büyükbaş-Küçükbaş Hayvancılık,116.848021,24.110,408.549664,1849
Resmi Daire Lojman,93.101238,29.585,141.698975,614
Şehit Aileleri ve Gaziler,87.035189,76.540,56.599681,2671
Balıkçılık ve Su Ürünleri Yetiştiriciliğ,85.358306,79.375,42.120066,124
İbadethane Isıtma/Soğutma/Lojman,81.283512,56.140,111.164648,10173
Doğal Afet Barınma,73.615948,73.865,39.066907,116
Mesken,55.590010,47.360,73.902931,1026609
"Kar Amacı Güden Dernek,Vakıf,Müze",43.780576,13.520,74.313572,243
Muhtarlık Hizmet Binaları,34.289765,9.140,60.020356,383
İbadethane Aydınlatma,32.435252,13.940,112.225490,3189
Belediye Park Bahçe Aydınlatma,31.951003,18.390,38.472449,349
"Bina Ort Kul (Asn,Hidr,Kapıcı Dai vb.)",29.965663,15.760,41.331395,3505
"Resmi Hayır Kurumları,Dernek,Vakıf,Müze",22.997456,8.820,42.496725,169
Cemevleri,10.713755,5.625,16.453958,916
Resmi İbadethane Isıtma/Soğutma/Lojman,9.097143,5.000,9.346247,7
Şantiye ve Geçici Aboneler (Belediye),1.949375,0.095,3.138306,16